name: Bug report
description: File a bug report
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: dropdown
    id: edition
    attributes:
      label: Edition
      description: What edition are you using?
      options:
        - Basic (Personal)
        - Plus
        - Complete (Pro)
    validations:
      required: true
  - type: textarea
    id: version
    attributes:
      label: "What version are you using?"
      description: "Tell us the exact version you are using."
      placeholder: "For example, 2.003"
    validations:
      required: true
  - type: dropdown
    id: variable-or-static
    attributes:
      label: What type of weights are you using?
      description: Tell us which weights you downloaded
      options:
        - Default (non-customized)
        - Variable (customized)
        - Static (customized)
    validations:
      required: true